### ISSUE TITLE
Repositories with hipblas hcc

### ISSUE THREAD

**Issue by JesseFarebro** [ROCmSoftwarePlatform/hiptensorflow#14]
I tried following the getting started steps exactly and continue to be puzzled by hipblas. It seems in the ROCM repository hipblas doesn't link shared library named `libhipblas-hcc.so` which hiptensorflow is looking for. I've tried building rocblas and hipblas from scratch to investigate a little but I don't see anywhere where `libhipblas-hcc` is being built. Here is the output from `python -c 'import tensorflow'`

```
I tensorflow/stream_executor/dso_loader.cc:130] Couldn't open CUDA library libhipblas-hcc.so. LD_LIBRARY_PATH:
I tensorflow/stream_executor/cuda/cuda_blas.cc:2295] Unable to load HIPBLAS DSO.
I tensorflow/stream_executor/dso_loader.cc:130] Couldn't open CUDA library libhipfft_hcc.so. LD_LIBRARY_PATH:
I tensorflow/stream_executor/cuda/cuda_fft.cc:344] Unable to load cuFFT DSO.
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libhip_hcc.so locally
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libhiprng.so locally
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libMIOpen.so locally
```

I wasn't even worried about libhipfft for the time being but the issues are probably related somehow. Thanks.

**Comment by whchung** [comment]
@JesseFarebro could you help try `export LD_LIBRARY_PATH=/opt/rocm/lib`

**Comment by sunway513** [comment]
@JesseFarebro , I believe this issue is due to the mismatch version of hipTF whl package and hipblas lib; we'll resolve it today and update this thread. 

In the meanwhile, you can try to build hip branch from source with this [doc](https://github.com/ROCmSoftwarePlatform/hiptensorflow/blob/hip/rocm_docs/tensorflow-build-from-source.md), or use our official [docker repo](https://hub.docker.com/r/rocm/hiptensorflow/) for quick deployment. 

Thanks for trying hipTF out :-)

**Comment by JesseFarebro** [comment]
Thanks! I'll build it from source for the time being. Not sure if you can comment on this or not but will there be a proper hcc version with rocm and MIOpen upstreamed later or will a HIP port be all there is for tensorflow.

**Comment by sunway513** [comment]
The hipTF whl package has been refreshed, and the issue should have been resolved if you pull and install the updated hipTF whl package again.
Here's the checksum for the updated hipTF package:
```
sha256sum tensorflow-1.0.1-cp27-cp27mu-linux_x86_64.whl 
fd6b6ff25db82e8eb5119098c6fcdcccde28472eb0d45443400343d24599f17d  tensorflow-1.0.1-cp27-cp27mu-linux_x86_64.whl

```
And the essential steps for you to resolve the issue:
```
sudo pip uninstall -y tensorflow
cd ~/ && wget http://repo.radeon.com/rocm/misc/tensorflow/tensorflow-1.0.1-cp27-cp27mu-linux_x86_64.whl
cd ~ && sudo pip install tensorflow-1.0.1-cp27-cp27mu-linux_x86_64.whl && rm tensorflow-1.0.1-cp27-cp27mu-linux_x86_64.whl

```

Regarding your question, this repo is hosting the HIP port of tensorflow. 
To build hipTF from source, what you'll need besides ROCm1.6.4 release is the bazel and hipTF code base.
You can start with those two sections of the document:
[Install Bazel](https://github.com/ROCmSoftwarePlatform/hiptensorflow/blob/hip/rocm_docs/tensorflow-build-from-source.md#install-bazel)
[Build hipTF](https://github.com/ROCmSoftwarePlatform/hiptensorflow/blob/hip/rocm_docs/tensorflow-build-from-source.md#build-hiptf)

**Comment by JesseFarebro** [comment]
@sunway513 I know this is the repository for the HIP port but I was wondering if there's work underway to upstream a non-hip rocm implementation?

**Comment by bensander** [comment]
@JesseFarebro - we are working on PR to upstream the HIP backend to TensorFlow, that will be the path to run on ROCM.  We anticipate this will be easy to keep in sync with the existing CUDA back-end since the codes are similar.
