### ISSUE TITLE
What types of operations are supported?

### ISSUE THREAD

**Issue by MSchuwalow** [ROCmSoftwarePlatform/hiptensorflow#27]
Hi.

I tried running a lstm based network using hiptensorflow.
The operations ran fine in the sense that no errors were thrown and nothing crashed, but the network completely failed to optimize.
Running the setup on a cpu/nvidia gpu leads to consistent convergence after around 300 epochs, while the loss of the version runnnig on hiptensorflow/rocm shows almost no change in loss.

Is this expected behavior in the sense that certain operations are known as broken and still have to be ported or is this more likely to be an issue with my setup? In the second case what kind of tests can I run to better diagnose the problem?

I'm using the latest rocm on ubuntu 16.04. hiptensorflow was compiled from source following the instructions.

**Comment by sunway513** [comment]
Hi @MSchuwalow , thanks for trying hipTF!

In your local hipTF environment, are you able to complete the examples in this [doc](https://github.com/ROCmSoftwarePlatform/hiptensorflow/blob/hip/rocm_docs/tensorflow-quickstart.md)?
If not, could you try our public hipTF docker image [here](https://hub.docker.com/r/rocm/hiptensorflow/)?

Currently, RNN operations are not supported by MIOpen, and we do not have such operations supported in hipTF yet; though not far away. 

To help to resolve the issue, could you share your model and steps to repro what you saw?

**Comment by MSchuwalow** [comment]
Alright. Thanks for the quick reply.

I can complete all the examples. But if RNNs are not yet supported we have found the culprit.
Is there an estimation when that feature will be added?

**Comment by sunway513** [comment]
Yes, we'll have RNN supported by MIOpen very soon; right after that, we'll integrate the RNN into hipTF. So it would be ready in a handful of weeks -- will update here and let you know :-)
