### ISSUE TITLE
There is no device can be used to do the computation

### ISSUE THREAD

**Issue by rahasayantan** [ROCmSoftwarePlatform/hiptensorflow#28]
===================
### Environment info
Operating System: UBUNTU => 16.04

Kernel information =>
===================================
dpkg --list | grep linux-image
ii  linux-image-4.11.0-kfd-compute-rocm-rel-1.6-180   4.11.0-kfd-compute-rocm-rel-1.6-180-1               amd64        Linux kernel, version 4.11.0-kfd-compute-rocm-rel-1.6-180
ii  linux-image-4.4.0-21-generic                      4.4.0-21.37                                         amd64        Linux kernel image for version 4.4.0 on 64 bit x86 SMP
ii  linux-image-4.4.0-98-generic                      4.4.0-98.121                                        amd64        Linux kernel image for version 4.4.0 on 64 bit x86 SMP
ii  linux-image-extra-4.4.0-21-generic                4.4.0-21.37                                         amd64        Linux kernel extra modules for version 4.4.0 on 64 bit x86 SMP
ii  linux-image-extra-4.4.0-98-generic                4.4.0-98.121                                        amd64        Linux kernel extra modules for version 4.4.0 on 64 bit x86 SMP
ii  linux-image-generic                               4.4.0.98.103                                        amd64        Generic Linux kernel image

How did I install?
================================
I started with a clean install of Ubuntu. Followed the basic install steps provided on the following link.
https://github.com/ROCmSoftwarePlatform/hiptensorflow/blob/hip/rocm_docs/tensorflow-install-basic.md
I faced no issues till i executed the example codes given on:
https://github.com/ROCmSoftwarePlatform/hiptensorflow/blob/hip/rocm_docs/tensorflow-quickstart.md

When I execute the following, i get error.
cd ~/models/tutorials/image/mnist

export HIP_VISIBLE_DEVICES=0
export HSA_ENABLE_SDMA=0
python ./convolutional.py 

Error
=====================
sayantan@sayantan-Inspiron-5559:~/models/tutorials/image/mnist$ python ./convolutional.py 
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libhipblas.so locally
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libhipfft.so locally
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libhip_hcc.so locally
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libhiprng.so locally
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libMIOpen.so locally
Extracting data/train-images-idx3-ubyte.gz
Extracting data/train-labels-idx1-ubyte.gz
Extracting data/t10k-images-idx3-ubyte.gz
Extracting data/t10k-labels-idx1-ubyte.gz
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
There is no device can be used to do the computation

===================
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libhipblas.so locally
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libhipfft.so locally
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libhip_hcc.so locally
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libhiprng.so locally
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libMIOpen.so locally
1.0.1

=============================
/opt/rocm/bin/hipconfig
Result=>>>>

HIP version  : 1.3.17385

== hipconfig
HIP_PATH     : /opt/rocm/hip
HIP_PLATFORM : nvcc
CPP_CONFIG   :  -D__HIP_PLATFORM_NVCC__=  -I/opt/rocm/hip/include -I/usr/local/cuda/include

== nvcc
Can't exec "nvcc": No such file or directory at /opt/rocm/bin/hipconfig line 143.

=== Environment Variables
PATH=/opt/rocm/hcc/bin:/opt/rocm/hip/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
HIP_PATH=/opt/rocm/hip
HCC_HOME=/opt/rocm/hcc

== Linux Kernel
Hostname     : sayantan-Inspiron-5559
Linux sayantan-Inspiron-5559 4.11.0-kfd-compute-rocm-rel-1.6-180 #1 SMP Tue Oct 10 08:15:38 CDT 2017 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

==================================
sudo lshw -c video

Result=>
  *-display               
       description: VGA compatible controller
       product: Sky Lake Integrated Graphics
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 07
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:277 memory:d1000000-d1ffffff memory:b0000000-bfffffff ioport:f000(size=64) memory:c0000-dffff
  *-display
       description: Display controller
       product: Sun XT [Radeon HD 8670A/8670M/8690M / R5 M330]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:01:00.0
       version: 81
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi bus_master cap_list rom
       configuration: driver=radeon latency=0
       resources: irq:278 memory:c0000000-cfffffff memory:d0000000-d003ffff ioport:e000(size=256) memory:d0040000-d005ffff

==================================>

lspci -nnk | grep -i vga -A3 
00:02.0 VGA compatible controller [0300]: Intel Corporation Sky Lake Integrated Graphics [8086:1916] (rev 07)
	DeviceName:  Onboard IGD
	Subsystem: Dell Skylake Integrated Graphics [1028:06b2]
	Kernel driver in use: i915

=================================
cd /opt/rocm/hsa/sample
make
./vector_copy

Initializing the hsa runtime succeeded.
Checking finalizer 1.0 extension support succeeded.
Generating function table for finalizer succeeded.
Getting a gpu agent failed.

Can you please help with this error.

Thanks and regards
Sayantan

**Comment by bensander** [comment]
Thank you for detailed issue report.  
It looks like the AMDGPU graphics driver failed to detect your GPU:
HIP_PLATFORM : nvcc

Is this your card:
product: Sun XT [Radeon HD 8670A/8670M/8690M / R5 M330]

I believe this is not on the supported card list?

**Comment by rahasayantan** [comment]
R5 M335. Is there any chance that this will be supported in recent future?
Thanks and regards
Sayantan

**Comment by whchung** [comment]
@rahasayantan the device was dated back in 2013 and wouldn't be supported.

**Comment by mmmmming18** [comment]
Hi everyone, I got the same error with my Vega FE. I am running on Ubuntu 16.04. 

/opt/rocm/bin/hipconfig

HIP version  : 1.4.17494

== hipconfig
HIP_PATH     : /opt/rocm/hip
HIP_PLATFORM : hcc
CPP_CONFIG   :  -D__HIP_PLATFORM_HCC__=   -I/opt/rocm/hip/include -I/opt/rocm/hcc/include

== hcc
HSA_PATH     : /opt/rocm/hsa
HCC_HOME     : /opt/rocm/hcc
HCC clang version 6.0.0 (ssh://gerritgit/compute/ec/hcc-tot/clang 42ceed861a212d9bd0aef883ee7981144f3ecc02) (ssh://gerritgit/compute/ec/hcc-tot/llvm 23e086be6f627e6e983c6789d2e77da6bf85ebb6) (based on HCC 1.1.17493-2f85d8a-42ceed8-23e086b )
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/hcc/bin
Can't exec "/opt/rocm/hcc/compiler/bin/llc": No such file or directory at /opt/rocm/bin/hipconfig line 132.
HCC-cxxflags :  -hc -std=c++amp -I/opt/rocm/hcc/includeHCC-ldflags  :  -hc -std=c++amp -L/opt/rocm/hcc/lib -Wl,--rpath=/opt/rocm/hcc/lib -ldl -lm -lpthread -lunwind -lhc_am -Wl,--whole-archive -lmcwamp -Wl,--no-whole-archive

=== Environment Variables
PATH=/home/mcong/cmake-3.4.1-Linux-x86_64/bin:/opt/rocm/hcc/bin:/opt/rocm/hip/bin:/home/mcong/bin:/home/mcong/.local/bin:/usr/local/cuda-8.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
LD_LIBRARY_PATH=/opt/rocm/lib
HIP_PLATFORM=hcc
HIP_PATH=/opt/rocm/hip
HIP_VISIBLE_DEVICES=0
HCC_HOME=/opt/rocm/hcc

== Linux Kernel
Hostname     : databurner01
Linux databurner01 4.13.0-31-generic #34~16.04.1-Ubuntu SMP Fri Jan 19 17:11:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

**Comment by whchung** [comment]
@mmmmming18 could you verify if you have followed steps at https://github.com/RadeonOpenCompute/ROCm to get ROCm stack properly installed, and can verify the installation building `/opt/rocm/hsa/sample` and run `vector_copy` inside it.

**Comment by mmmmming18** [comment]
Thanks for your help!

/opt/rocm/hsa/sample$ sudo make
gcc -c -I/opt/rocm/include -o vector_copy.o vector_copy.c -std=c99
gcc -Wl,--unresolved-symbols=ignore-in-shared-libs vector_copy.o -L/opt/rocm/lib -lhsa-runtime64 -o vector_copy

/opt/rocm/hsa/sample$ ./vector_copy
Initializing the hsa runtime succeeded.
Checking finalizer 1.0 extension support succeeded.
Generating function table for finalizer succeeded.
Getting a gpu agent succeeded.
Querying the agent name succeeded.
The agent name is gfx900.
Querying the agent maximum queue size succeeded.
The maximum queue size is 131072.
Creating the queue succeeded.
"Obtaining machine model" succeeded.
"Getting agent profile" succeeded.
Create the program succeeded.
Adding the brig module to the program succeeded.
Query the agents isa succeeded.
Finalizing the program succeeded.
Destroying the program succeeded.
Create the executable succeeded.
Loading the code object succeeded.
Freeze the executable succeeded.
Extract the symbol from the executable succeeded.
Extracting the symbol from the executable succeeded.
Extracting the kernarg segment size from the executable succeeded.
Extracting the group segment size from the executable succeeded.
Extracting the private segment from the executable succeeded.
Creating a HSA signal succeeded.
Finding a fine grained memory region succeeded.
Allocating argument memory for input parameter succeeded.
Allocating argument memory for output parameter succeeded.
Finding a kernarg memory region succeeded.
Allocating kernel argument memory buffer succeeded.
Dispatching the kernel succeeded.
Passed validation.
Freeing kernel argument memory buffer succeeded.
Destroying the signal succeeded.
Destroying the executable succeeded.
Destroying the code object succeeded.
Destroying the queue succeeded.
Freeing in argument memory buffer succeeded.
Freeing out argument memory buffer succeeded.
Shutting down the runtime succeeded.

**Comment by mmmmming18** [comment]
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 61, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: _ZN8hip_impl18unlock_stream_hip_EP12ihipStream_tPvPKcPN2hc16accelerator_viewE


Failed to load the native TensorFlow runtime.

See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#import_error

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by whchung** [comment]
@mmmmming18 could raise another ticket. From the look of your log it seems it's version mismatch between ROCm stack and TensorFlow binary package.

@sunway513 could you share the public container image for 1.7?

**Comment by sunway513** [comment]
@whchung , sure, will do.

**Comment by Dekken** [comment]
I'm seeing this on a VEGA RX 64 https://github.com/RadeonOpenCompute/ROCm-docker/issues/32

hsa/vector_copy builds and runs without failure

**Comment by Sumenia** [comment]
As far as I am concerned, it runs fine with rocm 1.7.1 on ubuntu 16.04 host with AMD VEGA 56 through docker hub image https://hub.docker.com/r/rocm/hiptensorflow/tags/  Don't forget to specify the tag `rocm1.7` when you pull or run it

**Comment by Dekken** [comment]
That's good, I didn't notice 1.7 was pushed to docker hub (11 days ago) 

that's should make somethings easier
