### ISSUE TITLE
How do I set up tensorflow to use hip/ROCm?

### ISSUE THREAD

**Issue by briansp2020** [ROCmSoftwarePlatform/hiptensorflow#29]
Sorry for abusing issues for questions.
I'm trying to set up tensorflow to use my Fury Nano on Ryzen 7 1800X machine running Ubuntu 16.0.3 with ROCm 1.6-180.

I followed https://github.com/ROCmSoftwarePlatform/hiptensorflow/blob/hip/rocm_docs/tensorflow-install-basic.md but I'm not sure if it is properly installed.

When I check the version of tensorflow
> python -c "import tensorflow; print(tensorflow.__version__)"
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libhipblas.so locally
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libhipfft.so locally
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libhip_hcc.so locally
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libhiprng.so locally
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libMIOpen.so locally
1.0.1

I assume it is expected that tensorflow thinks it is using CUDA?

Since I'm not sure how to run https://github.com/soumith/convnet-benchmarks/tree/master/tensorflow using the script, I just ran benchmark_vgg.py
> python benchmark_vgg.py
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libhipblas.so locally
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libhipfft.so locally
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libhip_hcc.so locally
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libhiprng.so locally
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libMIOpen.so locally
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/stream_executor/cuda/cuda_driver.cc:633] creating context when one is currently active; existing: 0x7f6ddb4bbb10
I tensorflow/core/common_runtime/gpu/gpu_device.cc:892] Found device 0 with properties: 
name: Fiji [Radeon R9 FURY / NANO Series]
major: 3 minor: 0 memoryClockRate (GHz) 1
pciBusID 0000:09:00.0
Total memory: 4.00GiB
Free memory: 3.75GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:913] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:972] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Fiji [Radeon R9 FURY / NANO Series], pci bus id: 0000:09:00.0)
I tensorflow/core/kernels/conv_ops.cc:604] running auto-tune for Convolve
MIOpen Error: /data/repo/MIOpen/src/hip/handlehip.cpp:68: Memory not available to allocate buffer: 822083584
F tensorflow/stream_executor/cuda/miopen_dnn.cc:1831] Check failed: status == miopenStatusSuccess (7 vs. 0)Unable to find a suitable algorithm for doing forward convolution
Aborted (core dumped)

**Comment by bensander** [comment]
Hi Brian - it looks like you ran out of memory:
MIOpen Error: /data/repo/MIOpen/src/hip/handlehip.cpp:68: Memory not available to allocate buffer: 822083584

VGG uses a large amount of memory and may not fit on your Fiji.  Can you reduce the batch size (--batch_size 32 or 16 ) or run one of the other benchmarks (benchmark_alexnet.py) to verify the config?

**Comment by briansp2020** [comment]
Hi Ben,
Thanks for the fast response. benchmark_alexnet.py fihisned without error. Reducing the batch size allowed benchmark_vgg.py to finish as well.

If I get RX Vega 56, will I be able to run benchmark_vgg.py without modification? What GPU is best supported by ROCm ML libraries at the moment. I'm just starting to learn ML framework and, though I like tinkering with ROCm & AMD GPUs, my first goal is to learn ML framework.

**Comment by bensander** [comment]
The vega 56 should work - IIRC it has 8GB memory while your Fiji has just 4.    
Vega is the best supported architecture right now.

**Comment by briansp2020** [comment]
Thanks for the help. I was able to get Keras to work with hipTF.
http://briansp2020.github.io/2017/11/05/fast_ai_ROCm/
