### ISSUE TITLE
Building from source

### ISSUE THREAD

**Issue by briansp2020** [ROCmSoftwarePlatform/hiptensorflow#33]
I'm trying to build hipTensorFlow from source. But I'm getting the following error.

> @Ryzen1800X:~/git/hiptensorflow$ bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
INFO: Found 1 target...
INFO: From Executing genrule //tensorflow/core:version_info_gen [for host]:
fatal: No names found, cannot describe anything.
ERROR: missing input file '@eigen_archive//:COPYING.MPL2'.
ERROR: /home/briansp/.cache/bazel/_bazel_briansp/571ae586fecf83b9a6234cf61f8c1b93/external/grpc/BUILD.bazel:71:1: C++ compilation of rule '@grpc//:gpr' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections ... (remaining 34 argument(s) skipped): com.google.devtools.build.lib.shell.AbnormalTerminationException: Process terminated by signal 15.
ERROR: /home/briansp/git/hiptensorflow/tensorflow/tools/pip_package/BUILD:102:1: //tensorflow/tools/pip_package:build_pip_package: missing input file '@eigen_archive//:COPYING.MPL2'.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/briansp/git/hiptensorflow/tensorflow/tools/pip_package/BUILD:102:1 1 input file(s) do not exist.
INFO: Elapsed time: 1.800s, Critical Path: 0.61s

I was able to install and use the prebuilt hipTensorFlow from http://repo.radeon.com/rocm/misc/tensorflow/

I'm following https://github.com/ROCmSoftwarePlatform/hiptensorflow/blob/hip/rocm_docs/tensorflow-build-from-source.md but did not build hcc/hip/etc. Do I have to build them in order to build TensorFlow successfully?

Any help would be appreciated.

Thanks

**Comment by whchung** [comment]
@briansp2020 Building hipTensorFlow from source requires you install every dependent packages according to the steps described in the markdown text.

**Comment by briansp2020** [comment]
The main problem was that I installed hipEigen, following the instructions from the hipEigen repo (cmake & make install).
After cloning the hipEigen repo to /opt/rocm, I was able to built it. Not sure why the hipEigen installation instruction does not work...
