### ISSUE TITLE
Performance issues on a certain workload 

### ISSUE THREAD

**Issue by masahi** [ROCmSoftwarePlatform/hiptensorflow#34]
Hi, I am running fast neural style transfer code [here](https://github.com/lengstrom/fast-style-transfer) on hiptensorflow.

Both inference and training worked on R9 Nano, but it's slow. 

For inference, it took 1.2 second to style transfer a 1024×680 image, while the same code running on GTX 1050 Ti with cudnn can do it in 0.25 sec. The author of the repo says Maxwell Titan X can do it in 0.1 sec.

For training, it took 1.6 second per batch for forward and backward. The batch size is [4, 3, 256, 256].
GTX 1050 Ti took 0.9 sec.

These numbers are obtained after auto tuning in the first kernel call. I ran the same forward and/or backward 10 times to amortize the overhead of first call. I found that without auto tuning, it can be more than 2x slower. For backward, without auto tuning it takes 3.8 per batch.

I profiled inference part under codexl. The command is
```
$ python evaluate.py --checkpoint=ckpt/scream.ckpt --in-path=examples/content/stata.jpg --out-path=out
```
The profile result is below. It says 90 % of compute is spent on hip reduction kernels?

 First of all, I don't know where this hip kernel calls are coming from. I profiled the same code under nvprof on cuda but I didn't find equivalent eigen kernel calls. The network definition is [here](https://github.com/lengstrom/fast-style-transfer/blob/master/src/transform.py)

Second, some invocations of these hip reduction kernels are really slow, and they are killing the performance. The kernels from miopen look fine, except one invocation of  miog_betac_alphaab  which took 100 msec. I'm assuming it is gemm. I don't understand why there is only one slow invocation, when I am running the same code 10 times. But if this invocation is occurring during auto tuning, this makes sense.

Can you help me make sense of this result? I apologize if I am missing something or doing something completely wrong.

![fast-neural-style-tf-timeline](https://user-images.githubusercontent.com/1776403/32671472-e1325a7a-c68a-11e7-8de4-45eccc27b148.png)
[
Full result in CSV](https://drive.google.com/open?id=12_yCG0QpHvyZSAaIrRqisjVUlPCwzilZ)

**Comment by sunway513** [comment]
@masahi , thanks for trying hipTF!
Let's first make sure you have configured hipTF correctly. Can you provide the log from the following command:
`/opt/rocm/bin/rocm-smi`
Second, I'm suspecting hipTF is using a different path than NV -- there're some ops not yet supported by MIOpen, thus you've seen additional kernels not shown in NV path; could you look more on that path?

**Comment by masahi** [comment]
@sunway513 
```
$ /opt/rocm/bin/rocm-smi


====================    ROCm System Management Interface    ====================
================================================================================
 GPU  DID    Temp     AvgPwr   SCLK     MCLK     Fan      Perf    OverDrive  ECC
  0   7300   25.0c    10.31W   300Mhz   500Mhz   18.82%   auto      0%       N/A      
================================================================================
====================           End of ROCm SMI Log          ====================
 
```

I can dig into this issue in more detail, but I'm not going to build hiptensorflow from source. It looks complicated :)

Do you know if all convolutional layers are dispatched to miopen, or this reduction hip kernels might be plain convolution implemented in hip?

**Comment by sunway513** [comment]
Thanks, you may try to lock the SCLK to 7 and MCLK to 3 for maximum performance, please check `/opt/rocm/bin/rocm-smi -h`

Could you also provide the log for HIP configure:
`/opt/rocm/hip/bin/hipconfig`

Conv layers have been fully ported to MIOpen, however, the reduction kernel seems still using Eigen implementation. 
I would suspect NV also uses Eigen kernels here; if not, could you identify which kernel they actually used?

**Comment by masahi** [comment]
```
$ /opt/rocm/hip/bin/hipconfig 
HIP version  : 1.3.17385

== hipconfig
HIP_PATH     : /opt/rocm/hip
HIP_PLATFORM : hcc
CPP_CONFIG   :  -D__HIP_PLATFORM_HCC__=   -I/opt/rocm/hip/include -I/opt/rocm/hcc/include

== hcc
HSA_PATH     : /opt/rocm/hsa
HCC_HOME     : /opt/rocm/hcc
HCC clang version 6.0.0  (based on HCC 1.0.17412-f590a25-821e6d8-64e7fc7 )
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/hcc/bin
Can't exec "/opt/rocm/hcc/compiler/bin/llc": No such file or directory at /opt/rocm/hip/bin/hipconfig line 132.
HCC-cxxflags :  -hc -std=c++amp -I/opt/rocm/hcc/includeHCC-ldflags  :  -hc -std=c++amp -L/opt/rocm/hcc/lib -Wl,--rpath=/opt/rocm/hcc/lib -ldl -lm -lpthread -lunwind -Wl,--whole-archive -lmcwamp -Wl,--no-whole-archive

=== Environment Variables
PATH=/opt/rocm/hcc/bin:/opt/rocm/hip/bin:/home/masa/anaconda3/bin:/home/masa/bin:/home/masa/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/rocm/bin:/home/masa/rtags/build/bin:/home/masa/.cabal/bin
LD_LIBRARY_PATH=:/opt/CodeXL_2.5-25:/usr/lib/x86_64-linux-gnu/:/opt/CodeXL_2.5-25/RuntimeLibs/QT/:/opt/rocm/lib:/home/masa/anaconda3/lib
HIP_PLATFORM=hcc
HIP_PATH=/opt/rocm/hip
HCC_HOME=/opt/rocm/hcc

== Linux Kernel
Hostname     : masa-System-Product-Name
Linux masa-System-Product-Name 4.11.0-kfd-compute-rocm-rel-1.6-180 #1 SMP Tue Oct 10 08:15:38 CDT 2017 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

```

I put the output of nvprof --print-gpu-summary [here](https://gist.github.com/masahi/0ec49b6c71c306896381588f551af657)
It does use eigen kernels, but different ones.

**Comment by masahi** [comment]
@sunway513 the network uses many 1x1 convolution, see [here](https://github.com/lengstrom/fast-style-transfer/blob/master/src/transform.py#L46)

Are you sure all conv ops are done by miopen? In profile I am only seeing 
*sp3AsmConv3x3F (winograd?)
*sp3AsmConvRxSF (winograd?)
*miog_alphaab and miog_betac_alphaab (gemm based conv?)

But miopen has 1x1 convolution right? It doesn't show up in codexl.
Is it possible that eigen kernels are doing many 1x1 convolution?

Other suspect is tf.nn.moments(...) [here](https://github.com/lengstrom/fast-style-transfer/blob/master/src/transform.py#L52)
It is called after all conv layers, and it should be using reduction inside.

**Comment by masahi** [comment]
@sunway513 ok, I think I now understand most of the profiling result.

Hip reduction kernels are definitely happening at tf.nn.moments(...).
Since there are 16 calls to tf.nn.moments and profiling shows that there are 48 reductions per one forward, tf.nn.moments should be doing 3 reductions per call.

For some reasions, some of the reduction calls are taking more than 200 msec.

**Comment by bensander** [comment]
This looks like similar issue that we resolved with the HIP runtime - proper reporting of shared memory size, and also changing compute cap number to 3 which enabled TF to select more optimal code paths for the reduction kernels.  That fix is avail in our open-source report https://github.com/ROCm-Developer-Tools/HIP.    If you are comfortable building HIP from source you can follow instructions there to pull the latest code and build.

**Comment by masahi** [comment]
@bensander I built the latest HIP from source, but it didn't help.

I think the slow kernel is one of those in [this file](https://github.com/ROCmSoftwarePlatform/hipeigen/blob/upstream/unsupported/Eigen/CXX11/src/Tensor/TensorReductionHip.h), but I don't know which one. The kernel name shown in CodeXL is something like _cxxamp_trampoline, which is a garbage. 

I also don't know exactly when slow invocation happens with what input.

**Comment by whchung** [comment]
@masahi could you try change this line:
https://github.com/ROCmSoftwarePlatform/hipeigen/blob/upstream/unsupported/Eigen/CXX11/src/Tensor/TensorReduction.h#L494

from:

```
!RunningOnGPU))) {
```

to:

```
!RunningOnGPU)) && false /*XXX - hack to disable this reduction path*/) {
```

**Comment by masahi** [comment]
@whchung thanks, I will try later (away from my pc now).

Do I need to build hiptensorflow from source?

**Comment by whchung** [comment]
@masahi yes. `hiptensorflow` includes `hipeigen` as a collection of header files. so you need to rebuild it.

**Comment by masahi** [comment]
@whchung alright, I'll go ahead and build things.

**Comment by masahi** [comment]
@whchung I'm getting this error when building hiptensorflow. Have you seen this error? Looks like this "undeclared inclusion" error is a common error people encounter when building tensorflow from source.

I built hcc, hip, and other libraries from source.

```
ERROR: /home/masa/project/rocm/hiptensorflow/tensorflow/contrib/image/BUILD:18:1: undeclared inclusion(s) in rule '//tensorflow/contrib/image:python/ops/_image_ops_gpu':
this rule is missing dependency declarations for the following files included by 'tensorflow/contrib/image/kernels/image_ops_gpu.cu.cc':
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/stdint.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/stddef.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/stdarg.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/__stddef_max_align_t.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/limits.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/x86intrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/ia32intrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/immintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/mmintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/xmmintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/mm_malloc.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/emmintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/f16cintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/pmmintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/tmmintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/smmintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/wmmintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/__wmmintrin_aes.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/__wmmintrin_pclmul.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/clflushoptintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/clwbintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/avxintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/avx2intrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/bmiintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/bmi2intrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/lzcntintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/fmaintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/avx512fintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/avx512vlintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/avx512bwintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/avx512cdintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/avx512vpopcntdqintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/avx512dqintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/avx512vlbwintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/avx512vlcdintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/avx512vldqintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/avx512erintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/avx512ifmaintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/avx512ifmavlintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/avx512vbmiintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/avx512vbmivlintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/avx512pfintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/pkuintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/rtmintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/xtestintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/shaintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/fxsrintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/xsaveintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/xsaveoptintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/xsavecintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/xsavesintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/adxintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/mm3dnow.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/prfchwintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/popcntintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/rdseedintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/ammintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/fma4intrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/xopintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/tbmintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/lwpintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/mwaitxintrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/clzerointrin.h'
  '/opt/rocm/hcc-1.2/lib/clang/6.0.0/include/float.h'.
```

**Comment by 7SK** [comment]
@masahi the build issue is resolved on hip-develop branch, please try now

**Comment by masahi** [comment]
@7SK ok, the build succeeds now with hip-develop branch, thanks.

**Comment by masahi** [comment]
@whchung you change doesn't help me. In fact, the condition

```
if((RunningFullReduction && RunningOnSycl) ||(RunningFullReduction &&
        internal::FullReducer<Self, Op, Device>::HasOptimizedImplementation &&
        ((RunningOnGPU && (m_device.majorDeviceVersion() >= 3)) ||
         !RunningOnGPU))) {}
```
always evaluates to false even without your change, because RunningFullReduction is always 0 (I checked it).
So this branch is never taken.

Instead,[ this branch ](https://github.com/ROCmSoftwarePlatform/hipeigen/blob/upstream/unsupported/Eigen/CXX11/src/Tensor/TensorReduction.h#L518)is always taken.

My test script is [here](https://gist.github.com/masahi/d854758758f5c2f1d396e364ffbca63e). When I run this script with this command, 

`python evaluate.py --checkpoint=ckpt/scream.ckpt --in-path=examples/content/stata.jpg --out-path=out`

here is the output I get. My card is R9 Nano.
```
$ python evaluate.py --checkpoint=ckpt/scream.ckpt --in-path=examples/content/stata.jpg --out-path=out
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libhipblas.so locally
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libhipfft.so locally
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libhip_hcc.so locally
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libhiprng.so locally
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libMIOpen.so locally
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/stream_executor/cuda/cuda_driver.cc:633] creating context when one is currently active; existing: 0x2436230
I tensorflow/core/common_runtime/gpu/gpu_device.cc:886] Found device 0 with properties: 
name: Fiji [Radeon R9 FURY / NANO Series]
major: 3 minor: 0 memoryClockRate (GHz) 1
pciBusID 0000:01:00.0
Total memory: 4.00GiB
Free memory: 3.75GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:907] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:917] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:966] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Fiji [Radeon R9 FURY / NANO Series], pci bus id: 0000:01:00.0)
batch_shape (1, 679, 1024, 3)
I tensorflow/core/kernels/conv_ops.cc:604] running auto-tune for Convolve
I tensorflow/core/kernels/conv_ops.cc:604] running auto-tune for Convolve
I tensorflow/core/kernels/conv_ops.cc:604] running auto-tune for Convolve
I tensorflow/core/kernels/conv_ops.cc:604] running auto-tune for Convolve
I tensorflow/core/kernels/conv_grad_input_ops.cc:764] running auto-tune for Backward-Data
I tensorflow/core/kernels/conv_grad_input_ops.cc:764] running auto-tune for Backward-Data
I tensorflow/core/kernels/conv_ops.cc:604] running auto-tune for Convolve
Elapsed 1.939539 sec.
Elapsed 1.391111 sec.
Elapsed 1.385673 sec.
Elapsed 1.393700 sec.
Elapsed 1.355533 sec.
```
Can you run the above script and tell me what number you get? 
If this issue is happening only on my system, I can close this.

**Comment by whchung** [comment]
Please kindly try https://github.com/ROCmSoftwarePlatform/tensorflow/ and open the issue there in case it persists. This project has been deprecated and I'll close this repository very soon. Thanks for your understanding.
