### ISSUE TITLE
AttributeError: 'module' object has no attribute 'get_or_create_global_step'

### ISSUE THREAD

**Issue by MyAusweis** [ROCmSoftwarePlatform/hiptensorflow#41]
Dear All,

I have tried this AMD version of tensorflow using train.py in from models/research/object_detection, when i run it the cuda has opened successfully but  it showed "AttributeError: 'module' object has no attribute 'get_or_create_global_step'. i use ubuntu 16.04, RAM 8GB, python 2.7.12. laptop lenovo G50-80 I7 5500 with Graphics Radeon

anyone can help me ?

**Comment by 7SK** [comment]
Hi @MyAusweis ,
tf.train.get_or_create_global_step is not part of current version of hiptensorflow. Please use this workaround for the time being https://github.com/7SK/models/commit/db1a4dcd8d3f12bcdf9ba4c274cda9ed089985a5

**Comment by MyAusweis** [comment]
i'm new to github, pls tell me how to arrange to the models for the id 7SK/models@db1a4dc thx

**Comment by MyAusweis** [comment]
Now after i replace the value of optimizer_builder.py with your sugestion 7SK@models, i found error :

File "/home/user/lat-toy/object_detection/utils/variables_helper.py", line 122, in get_variables_available_in_checkpoint
    ckpt_reader = tf.train.NewCheckpointReader(checkpoint_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 110, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern), status)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for model.ckpt 

event i have put 
 1. model.ckpt.data-00000-of-00001
 2. model.ckpt.index
 3. model.ckpt.meta
 4. ssd_mobilenet_v1_pets.config
 5. frozen_inference_graph.pb
 6. graph.pbtxt
 7. toy_label_map.pbtxt

same with train.py 

here the instruction i use for : python train.py --pipeline_config_path=./ssd_mobilenet_v1_pets.config --train_dir=.

**Comment by 7SK** [comment]
Hi @MyAusweis, you need to update the config to provide the path for the following:
https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/ssd_mobilenet_v1_pets.config#L158
https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/ssd_mobilenet_v1_pets.config#L175
https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/ssd_mobilenet_v1_pets.config#L189

please read https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/configuring_jobs.md

Thanks

**Comment by MyAusweis** [comment]
Thank you for your help, but i found another problem

user@user-Lenovo-G50-80:~/lat-toy$ python train.py --pipeline_config_path=./ssd_mobilenet_v1_pets.config --train_dir=.
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libhipblas.so locally
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libhipfft.so locally
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libhip_hcc.so locally
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libhiprng.so locally
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libMIOpen.so locally
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:Summary name /clone_loss is illegal; using clone_loss instead.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.

There is no device can be used to do the computation,  how can this happened ?

Thx

**Comment by parallelo** [comment]
Hi @MyAusweis, 

Taking a step back, we should first ensure that you have a working ROCm installation.  Are you able to run any of the HIP samples?  E.g. :
```
# cd /tmp && cp -r /opt/rocm/hip/samples/0_Intro/square . && cd square

# make clean && make
rm -f *.o *.out	
/opt/rocm/hip/bin/hipcc  square.hipref.cpp -o square.hip.out

# ./square.hip.out 
[...]
info: copy Host2Device
info: launch 'vector_square' kernel
info: copy Device2Host
info: check result
PASSED!
```

Best, 

Jeff

**Comment by MyAusweis** [comment]
Here the result

cd /tmp && cp -r /opt/rocm/hip/samples/0_Intro/square . && cd square
user@user-Lenovo-G50-80:/tmp/square$ make clean && make
rm -f *.o *.out	
/opt/rocm/hip/bin/hipcc  square.hipref.cpp -o square.hip.out
Can't exec "/usr/local/cuda/bin/nvcc": No such file or directory at /opt/rocm/hip/bin/hipcc line 498.
Died at /opt/rocm/hip/bin/hipcc line 498.
Makefile:14: recipe for target 'square.hip.out' failed
make: *** [square.hip.out] Error 2

**Comment by parallelo** [comment]
Hi @MyAusweis, 

It looks like you don't have a functional ROCm installation.  

Can you please follow the details on the ROCm site?  https://github.com/RadeonOpenCompute/ROCm

(E.g. ensure that `rocm` and `rocm-dev` are installed, and then verify that you can build & run HIP samples)

Keep us posted.  

Best, 

Jeff

**Comment by MyAusweis** [comment]
user@user-Lenovo-G50-80:/tmp/square$ /opt/rocm/bin/hipconfig --full
HIP version  : 1.3.17385

== hipconfig
HIP_PATH     : /opt/rocm
HIP_PLATFORM : nvcc
CPP_CONFIG   :  -D__HIP_PLATFORM_NVCC__=  -I/opt/rocm/include -I/usr/local/cuda/include

== nvcc
Can't exec "nvcc": No such file or directory at /opt/rocm/bin/hipconfig line 143.

=== Environment Variables
PATH=/home/user/bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin

== Linux Kernel
Hostname     : user-Lenovo-G50-80
Linux user-Lenovo-G50-80 4.11.0-kfd-compute-rocm-rel-1.6-180 #1 SMP Tue Oct 10 08:15:38 CDT 2017 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

**Comment by parallelo** [comment]
Hi @MyAusweis, 

Based on the output from `hipconfig`, it looks like your ROCm installation isn't set up correctly.  It isn't detecting a ROCm platform.  

Have you visited the ROCm GitHub site?  https://github.com/RadeonOpenCompute/ROCm

Based on the information on that page, is your target GPU supported?  Did you hit any errors when following that page's installation process?  

Best, 

Jeff

**Comment by MyAusweis** [comment]
how to verify it ? that my laptop support it

user@user-Lenovo-G50-80:/opt/rocm/hsa/sample$ uname -r
4.11.0-kfd-compute-rocm-rel-1.6-180

user@user-Lenovo-G50-80:/opt/rocm/hsa/sample$ ./vector_copy
Initializing the hsa runtime succeeded.
Checking finalizer 1.0 extension support succeeded.
Generating function table for finalizer succeeded.
Getting a gpu agent failed.

in lenovo g50-80 i7 5500 using graphic AMD Radeon R5-M330 2GB

**Comment by whchung** [comment]
@MyAusweis unfortunately since you are running on a laptop, your hardware is not supported by ROCm. please refer to:

https://rocm.github.io/hardware.html

for supported hardware.
