### ISSUE TITLE
HCC RUNTIME ERROR: Fail to find compatible kernel

### ISSUE THREAD

**Issue by MichaelMcCulloch** [ROCmSoftwarePlatform/hiptensorflow#43]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
[StackOverflow](https://stackoverflow.com/questions/47421290/hcc-runtime-error-when-trying-to-run-hiptensorflow-ubuntu-16-04-r9-290)
[GitHub](https://github.com/ROCmSoftwarePlatform/hipCaffe/issues/7)

### Environment info
Operating System:
Ubuntu 16.04.3 4.11.0-kfd-compute-rocm-rel-1.6-180
R9 290X x2

If installed from binary pip package, provide:

1. A link to the pip package you installed:
[package](http://repo.radeon.com/rocm/misc/tensorflow/tensorflow-1.0.1-cp27-cp27mu-linux_x86_64.whl)
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
[Pastebin](https://pastebin.com/12zY2aq0)

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
`python -c "import tensorflow; print(tensorflow.__version__)"`

**Comment by whchung** [comment]
@MichaelMcCulloch unfortunately R9 290X x2 is not in the supported hardware list ( https://rocm.github.io/hardware.html ) . Please consider get a compatible AMD GPU from the list to test hipTensorFlow.

**Comment by MichaelMcCulloch** [comment]
Ok thank you. Are there currently any plans to support Hawaii hardware? I ask only because support for Hawaii seemed to be added added in 1.2 IIRC, and is still mentioned in the 1.7 readme [here](https://github.com/RadeonOpenCompute/ROCm)

**Comment by whchung** [comment]
We do have limited support for Hawaii in ROCm stack for certain applications, but not in the plan for machine learning related applications.
