### ISSUE TITLE
Support macOS

### ISSUE THREAD

**Issue by tonysung** [ROCmSoftwarePlatform/hiptensorflow#44]
Please support macOS because all of it comes with Radeon GPUs.

**Comment by MonkeyChap** [comment]
Has anyone attempted this ?  I was about to have a go, but didn't want to waste time if it's not going to build.

**Comment by whchung** [comment]
Building TensorFlow on OSX is actually not hard. Getting it to run is. This project depends on https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver which is Linux-only at this moment.

**Comment by anton-matosov** [comment]
Will that work with VMWare Fusion VM with Ubuntu 16.04 as a guest OS then? 

P.S.
Host OS is MacBook Pro with i7-6700HQ CPU (VT-d and VT-x capable) and AMD Radeon Pro 460/Intel HD Graphics 530 GPUs.

**Comment by whchung** [comment]
ROCm for OSX is not in the roadmap for now.
