### ISSUE TITLE
LD Library Path

### ISSUE THREAD

**Issue by ArlasJ** [ROCmSoftwarePlatform/hiptensorflow#45]
Hello I am using a vega 64 graphic card on a debian linux machine.
Everytime I try to run tf I get following error:
```
I tensorflow/stream_executor/dso_loader.cc:130] Couldn't open CUDA library libhiprng.so. LD_LIBRARY_PATH: 
I tensorflow/stream_executor/cuda/cuda_rng.cc:338] Unable to load cuRAND DSO.
```

Can you help me?

Best regards,
Justin J.

**Comment by sunway513** [comment]
Hi @ArlasJ , 
Could you provide more information on your setup? ROCm1.6.4 or ROCm1.7?

**Comment by ArlasJ** [comment]
It is ROCm 1.7. 
Tried it with 4.15rc6 kernel cause of vega64 support.

**Comment by ArlasJ** [comment]
I solved the issue with I tensorflow/stream_executor/dso_loader.cc:130] Couldn't open CUDA library libMIOpen.so. LD_LIBRARY_PATH:

with reference to issue #35 

But libhiprng.so still remains.

**Comment by ArlasJ** [comment]
I think I found the problem,

I tried this one:
sudo modprobe -v amd-rng
insmod /lib/modules/4.15.0-rc6-custom/kernel/drivers/char/hw_random/amd-rng.ko 
modprobe: ERROR: could not insert 'amd_rng': No such device

the module can't find a device. I try to fix that.

**Comment by ArlasJ** [comment]
sudo ln -s libhiprand.so libhiprng.so

this works... I don't know if this solution is correct?

**Comment by sunway513** [comment]
Hi, hipTF requires hcRNG library, but it's not included in ROCm1.7 release -- we'll fix it.
In the meanwhile, please use the following command to build and install it from source: git clone ```
https://github.com/ROCmSoftwarePlatform/hcRNG.git ~/hcrng
cd ~/hcrng && bash build.sh && sudo dpkg -i ~/hcrng/build/*.deb
```

**Comment by Dekken** [comment]
I'm hitting this now, is hiprng available from the apt repo?

trying to build hcRNG has compile errors

```
/opt/rocm/hip/include/hip/hip_runtime_api.h:276:2: error: ("Must define exactly one of __HIP_PLATFORM_HCC__ or __HIP_PLATFORM_NVCC__");
#error("Must define exactly one of __HIP_PLATFORM_HCC__ or __HIP_PLATFORM_NVCC__");
```

**Comment by gstoner** [comment]
https://github.com/ROCmSoftwarePlatform/rocRAND

**Comment by Dekken** [comment]
reinstalling from apt hipblas appears to have solved my hiprng problem, I already had rocrand installed.
