### ISSUE TITLE
Encounter an opencl error while running MINST example

### ISSUE THREAD

**Issue by ws0zzg4569** [ROCmSoftwarePlatform/hiptensorflow#46]
Happy new year every one.
I'm new to ROCm and just want to configure the hiptf with my rx480, I followed the instruction of this [basic install guide](https://github.com/ROCmSoftwarePlatform/hiptensorflow/blob/hip/rocm_docs/tensorflow-install-basic.md), but got the following opencl error while running the MNIST example, search around and no idea how to solve this. Are there any one can help? Appreciating.
 
>georgelee@georgelee-System-Product-Name:~/models/tutorials/image/mnist$ python2 ./convolutional.py 
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libhipblas.so locally
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libhipfft.so locally
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libhip_hcc.so locally
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libhiprng.so locally
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libMIOpen.so locally
Extracting data/train-images-idx3-ubyte.gz
Extracting data/train-labels-idx1-ubyte.gz
Extracting data/t10k-images-idx3-ubyte.gz
Extracting data/t10k-labels-idx1-ubyte.gz
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/stream_executor/cuda/cuda_driver.cc:633] creating context when one is currently active; existing: 0x7ff9263ecc90
I tensorflow/core/common_runtime/gpu/gpu_device.cc:892] Found device 0 with properties: 
name: Device 67df
major: 3 minor: 0 memoryClockRate (GHz) 1.29
pciBusID 0000:27:00.0
Total memory: 8.00GiB
Free memory: 7.75GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:913] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:972] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Device 67df, pci bus id: 0000:27:00.0)
Initialized!
I tensorflow/core/kernels/conv_ops.cc:604] running auto-tune for Convolve
MIOpen(HIP): Warning [ReadFile] File is unreadable.
I tensorflow/core/kernels/conv_ops.cc:604] running auto-tune for Convolve
WARNING: Linking two modules of different data layouts: '/opt/rocm/opencl/lib/x86_64/bitcode/opencl.amdgcn.bc' is 'e-p:64:64-p1:64:64-p2:64:64-p3:32:32-p4:32:32-p5:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-A5' whereas 'llvm-link' is 'e-p:32:32-p1:64:64-p2:64:64-p3:32:32-p4:64:64-p5:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64'
WARNING: Linking two modules of different target triples: /opt/rocm/opencl/lib/x86_64/bitcode/opencl.amdgcn.bc' is 'amdgcn-amd-amdhsa-amdgizcl' whereas 'llvm-link' is 'amdgcn-amd-amdhsa-opencl'
WARNING: Linking two modules of different data layouts: '/opt/rocm/opencl/lib/x86_64/bitcode/ocml.amdgcn.bc' is 'e-p:64:64-p1:64:64-p2:64:64-p3:32:32-p4:32:32-p5:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-A5' whereas 'llvm-link' is 'e-p:32:32-p1:64:64-p2:64:64-p3:32:32-p4:64:64-p5:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64'
WARNING: Linking two modules of different target triples: /opt/rocm/opencl/lib/x86_64/bitcode/ocml.amdgcn.bc' is 'amdgcn-amd-amdhsa-amdgizcl' whereas 'llvm-link' is 'amdgcn-amd-amdhsa-opencl'
WARNING: Linking two modules of different data layouts: '/opt/rocm/opencl/lib/x86_64/bitcode/ockl.amdgcn.bc' is 'e-p:64:64-p1:64:64-p2:64:64-p3:32:32-p4:32:32-p5:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-A5' whereas 'llvm-link' is 'e-p:32:32-p1:64:64-p2:64:64-p3:32:32-p4:64:64-p5:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64'
WARNING: Linking two modules of different target triples: /opt/rocm/opencl/lib/x86_64/bitcode/ockl.amdgcn.bc' is 'amdgcn-amd-amdhsa-amdgizcl' whereas 'llvm-link' is 'amdgcn-amd-amdhsa-opencl'
WARNING: Linking two modules of different data layouts: '/opt/rocm/opencl/lib/x86_64/bitcode/irif.amdgcn.bc' is 'e-p:64:64-p1:64:64-p2:64:64-p3:32:32-p4:32:32-p5:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-A5' whereas 'llvm-link' is 'e-p:32:32-p1:64:64-p2:64:64-p3:32:32-p4:64:64-p5:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64'
WARNING: Linking two modules of different target triples: /opt/rocm/opencl/lib/x86_64/bitcode/irif.amdgcn.bc' is 'amdgcn-amd-amdhsa-amdgizcl' whereas 'llvm-link' is 'amdgcn-amd-amdhsa-opencl'
WARNING: Linking two modules of different data layouts: '/opt/rocm/opencl/lib/x86_64/bitcode/oclc_correctly_rounded_sqrt_off.amdgcn.bc' is 'e-p:64:64-p1:64:64-p2:64:64-p3:32:32-p4:32:32-p5:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-A5' whereas 'llvm-link' is 'e-p:32:32-p1:64:64-p2:64:64-p3:32:32-p4:64:64-p5:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64'
WARNING: Linking two modules of different target triples: /opt/rocm/opencl/lib/x86_64/bitcode/oclc_correctly_rounded_sqrt_off.amdgcn.bc' is 'amdgcn-amd-amdhsa-amdgizcl' whereas 'llvm-link' is 'amdgcn-amd-amdhsa-opencl'
WARNING: Linking two modules of different data layouts: '/opt/rocm/opencl/lib/x86_64/bitcode/oclc_daz_opt_on.amdgcn.bc' is 'e-p:64:64-p1:64:64-p2:64:64-p3:32:32-p4:32:32-p5:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-A5' whereas 'llvm-link' is 'e-p:32:32-p1:64:64-p2:64:64-p3:32:32-p4:64:64-p5:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64'
WARNING: Linking two modules of different target triples: /opt/rocm/opencl/lib/x86_64/bitcode/oclc_daz_opt_on.amdgcn.bc' is 'amdgcn-amd-amdhsa-amdgizcl' whereas 'llvm-link' is 'amdgcn-amd-amdhsa-opencl'
WARNING: Linking two modules of different data layouts: '/opt/rocm/opencl/lib/x86_64/bitcode/oclc_finite_only_off.amdgcn.bc' is 'e-p:64:64-p1:64:64-p2:64:64-p3:32:32-p4:32:32-p5:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-A5' whereas 'llvm-link' is 'e-p:32:32-p1:64:64-p2:64:64-p3:32:32-p4:64:64-p5:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64'
WARNING: Linking two modules of different target triples: /opt/rocm/opencl/lib/x86_64/bitcode/oclc_finite_only_off.amdgcn.bc' is 'amdgcn-amd-amdhsa-amdgizcl' whereas 'llvm-link' is 'amdgcn-amd-amdhsa-opencl'
WARNING: Linking two modules of different data layouts: '/opt/rocm/opencl/lib/x86_64/bitcode/oclc_isa_version_803.amdgcn.bc' is 'e-p:64:64-p1:64:64-p2:64:64-p3:32:32-p4:32:32-p5:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-A5' whereas 'llvm-link' is 'e-p:32:32-p1:64:64-p2:64:64-p3:32:32-p4:64:64-p5:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64'
WARNING: Linking two modules of different target triples: /opt/rocm/opencl/lib/x86_64/bitcode/oclc_isa_version_803.amdgcn.bc' is 'amdgcn-amd-amdhsa-amdgizcl' whereas 'llvm-link' is 'amdgcn-amd-amdhsa-opencl'
WARNING: Linking two modules of different data layouts: '/opt/rocm/opencl/lib/x86_64/bitcode/oclc_unsafe_math_off.amdgcn.bc' is 'e-p:64:64-p1:64:64-p2:64:64-p3:32:32-p4:32:32-p5:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-A5' whereas 'llvm-link' is 'e-p:32:32-p1:64:64-p2:64:64-p3:32:32-p4:64:64-p5:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64'
WARNING: Linking two modules of different target triples: /opt/rocm/opencl/lib/x86_64/bitcode/oclc_unsafe_math_off.amdgcn.bc' is 'amdgcn-amd-amdhsa-amdgizcl' whereas 'llvm-link' is 'amdgcn-amd-amdhsa-opencl'
/opt/rocm/opencl/bin/x86_64/ld.lld: error: can't create dynamic relocation R_AMDGPU_REL32_LO against symbol: atomic_cmpxchg(unsigned int volatile AS4*, unsigned int, unsigned int) in readonly segment; recompile object files with -fPIC

>\>>> defined in /tmp/tinygemm-0753eb.o
>\>>> referenced by /tmp/tinygemm-0753eb.o:(miog_alphaab)
/opt/rocm/opencl/bin/x86_64/ld.lld: error: can't create dynamic relocation R_AMDGPU_REL32_HI against symbol: atomic_cmpxchg(unsigned int volatile AS4*, unsigned int, unsigned int) in readonly segment; recompile object files with -fPIC

>\>>> defined in /tmp/tinygemm-0753eb.o
>\>>> referenced by /tmp/tinygemm-0753eb.o:(miog_alphaab)
/opt/rocm/opencl/bin/x86_64/ld.lld: error: can't create dynamic relocation R_AMDGPU_REL32_LO against symbol: atomic_cmpxchg(unsigned int volatile AS4*, unsigned int, unsigned int) in readonly segment; recompile object files with -fPIC

>\>>> defined in /tmp/tinygemm-0753eb.o
>\>>> referenced by /tmp/tinygemm-0753eb.o:(miog_alphaab)
/opt/rocm/opencl/bin/x86_64/ld.lld: error: can't create dynamic relocation R_AMDGPU_REL32_HI against symbol: atomic_cmpxchg(unsigned int volatile AS4*, unsigned int, unsigned int) in readonly segment; recompile object files with -fPIC

>\>>> defined in /tmp/tinygemm-0753eb.o
>\>>> referenced by /tmp/tinygemm-0753eb.o:(miog_alphaab)
/opt/rocm/opencl/bin/x86_64/ld.lld: error: can't create dynamic relocation R_AMDGPU_REL32_LO against symbol: atomic_cmpxchg(unsigned int volatile AS4*, unsigned int, unsigned int) in readonly segment; recompile object files with -fPIC

>\>>> defined in /tmp/tinygemm-0753eb.o
>\>>> referenced by /tmp/tinygemm-0753eb.o:(miog_alphaab)
/opt/rocm/opencl/bin/x86_64/ld.lld: error: can't create dynamic relocation R_AMDGPU_REL32_HI against symbol: atomic_cmpxchg(unsigned int volatile AS4*, unsigned int, unsigned int) in readonly segment; recompile object files with -fPIC

>\>>> defined in /tmp/tinygemm-0753eb.o
>\>>> referenced by /tmp/tinygemm-0753eb.o:(miog_alphaab)
/opt/rocm/opencl/bin/x86_64/ld.lld: error: can't create dynamic relocation R_AMDGPU_REL32_LO against symbol: atomic_cmpxchg(unsigned int volatile AS4*, unsigned int, unsigned int) in readonly segment; recompile object files with -fPIC

>\>>> defined in /tmp/tinygemm-0753eb.o
>\>>> referenced by /tmp/tinygemm-0753eb.o:(miog_alphaab)
/opt/rocm/opencl/bin/x86_64/ld.lld: error: can't create dynamic relocation R_AMDGPU_REL32_HI against symbol: atomic_cmpxchg(unsigned int volatile AS4*, unsigned int, unsigned int) in readonly segment; recompile object files with -fPIC

>\>>> defined in /tmp/tinygemm-0753eb.o
>\>>> referenced by /tmp/tinygemm-0753eb.o:(miog_alphaab)
/opt/rocm/opencl/bin/x86_64/ld.lld: error: can't create dynamic relocation R_AMDGPU_REL32_LO against symbol: atomic_cmpxchg(unsigned int volatile AS4*, unsigned int, unsigned int) in readonly segment; recompile object files with -fPIC

>\>>> defined in /tmp/tinygemm-0753eb.o
>\>>> referenced by /tmp/tinygemm-0753eb.o:(miog_alphaab)
/opt/rocm/opencl/bin/x86_64/ld.lld: error: can't create dynamic relocation R_AMDGPU_REL32_HI against symbol: atomic_cmpxchg(unsigned int volatile AS4*, unsigned int, unsigned int) in readonly segment; recompile object files with -fPIC

>\>>> defined in /tmp/tinygemm-0753eb.o
>\>>> referenced by /tmp/tinygemm-0753eb.o:(miog_alphaab)
clang: error: ld.lld command failed with exit code 1 (use -v to see invocation)
Segmentation fault(core dumped)

No idea why this repeated so many times and got this long...

**Comment by ws0zzg4569** [comment]
Seems to be the driver issue.

I try to reinstall a fresh ubuntu16.04, and redo all the steps, the GPU device can not found. seems forget the driver, but when install driver I got a low graphic BUG, can not display any GUI...no idea how to fix. Then I reinstall the Ubuntu 16.04 again, and Install amdgpu-pro (latest 17.50 for now, 16 will encounter a low graphic bug), then follow the step. 

After this, the hiprng will not installed correctly, need to build it manually.(from this solved [issue)](https://github.com/ROCmSoftwarePlatform/hiptensorflow/issues/15)
>git clone https://github.com/ROCmSoftwarePlatform/hcRNG.git ~/hcrng
cd ~/hcrng && bash build.sh && sudo dpkg -i ~/hcrng/build/*.deb

Finally! I got the MINST example run properly!
But the rest of example seems to have some tensorflow version problem
>Traceback (most recent call last):
  File "./resnet_main.py", line 212, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "./resnet_main.py", line 205, in main
    train(hps)
  File "./resnet_main.py", line 55, in train
    model.build_graph()
  File "/home/lzq/models/research/resnet/resnet_model.py", line 59, in build_graph
    self.global_step = tf.train.get_or_create_global_step()
AttributeError: 'module' object has no attribute 'get_or_create_global_step'

**Comment by whchung** [comment]
@ws0zzg4569 I'd like to ask @sunway513 to help you on the driver issue. But perhaps you can use the docker image ( https://hub.docker.com/r/rocm/hiptensorflow/ ) to begin faster.

For Python API issue, `hiptensorflow` is based on TensorFlow 1.0.1 so there might be changes in Python API. We are working on getting it upgraded to be in sync with tip of TensorFlow and would publish new releases soon.

**Comment by ws0zzg4569** [comment]
@whchung thanks! I think if it's the tensorflow api problem,  we can close it, the MINST now can run on the GPU smoothly. I'll try to modify the code of other example and check my set up.
Really glad I don't need to buy a Nvdia card....
