### ISSUE TITLE
tensorflow examples 'killed'

### ISSUE THREAD

**Issue by Dekken** [ROCmSoftwarePlatform/hiptensorflow#47]
After updating to latest ROCM (1.7?)

Running the python examples results in nothing but 

```Killed```

Debian 9 / VEGA Liquid RX

Happy to facilitate

**Comment by sunway513** [comment]
Hi Dekken, did you use the last public docker image? If so, that's because we have not released the ROCm1.7 docker image yet -- will be ready today and let you know.

**Comment by Dekken** [comment]
Hi @sunway513 

I had tested the previous docker image and it was fine, but I'm hoping to get this working natively as I'm not all that fond (familiar) with docker.

cheers

**Comment by sunway513** [comment]
Thanks for the additional info. We'll also update the hipTF pip package to work with the ROCm1.7 environment. In the meanwhile, you can try to build it from source, follow the instructions starting [here](https://github.com/ROCmSoftwarePlatform/hiptensorflow/blob/hip/rocm_docs/tensorflow-build-from-source.md#install-required-python-packages).

**Comment by Dekken** [comment]
will do, is there a doc on released versions that gets updated?

**Comment by sunway513** [comment]
you should be able to find the update notes from each of the ROCm component's github repository. 
But the biggest change for ROCm1.7 overall is that we change to use DKMS based KFD.
