### ISSUE TITLE
unpinned copy engine error of ROCm 1.7/hiptensorflow1.0.1

### ISSUE THREAD

**Issue by catsdogone** [ROCmSoftwarePlatform/hiptensorflow#50]
### Environment info
Operating System: Ubuntu 16.04.3
Installed version ROCm:  1.7 (hiptensorflow:rocm1.7-public-v4)
tensorflow/models: 
  git clone https://github.com/tensorflow/models.git
  git revert --no-commit a2b2088c52635b86f4a2ac70391118b9419b3c55
  cd models/tutorials/image/cifar10

  **unpinned copy engine error** when run:
  python cifar10_multi_gpu_train.py --num_gpus=4 --batch_size 8
  or
  python cifar10_multi_gpu_train.py --num_gpus=4 --batch_size 128

  whill it is ok when run with num_gpus=2:
  python cifar10_multi_gpu_train.py --num_gpus=2 --batch_size 128

 
[cifar10_multi_gpu_train_4gpu_log.txt](https://github.com/ROCmSoftwarePlatform/hiptensorflow/files/1621162/cifar10_multi_gpu_train_4gpu_log.txt)

**Comment by parallelo** [comment]
Hi @catsdogone, 

We've seen a similar issue previously with hipCaffe.  And if I remember correctly, we resolved it by moving from hcRNG to rocRAND.  

Can you please try this workaround to see if it has an effect?
```
export HCC_UNPINNED_COPY_MODE=2
```

Thanks, 

Jeff

**Comment by whchung** [comment]
Please kindly try https://github.com/ROCmSoftwarePlatform/tensorflow/ and open the issue there in case it persists. This project has been deprecated and I'll close this repository very soon. Thanks for your understanding.
