### ISSUE TITLE
docker image includes python3 tensorflow

### ISSUE THREAD

**Issue by Dekken** [ROCmSoftwarePlatform/hiptensorflow#51]
Is this done, or in the pipeline?

**Comment by whchung** [comment]
Right now the plan is to:
- publish releases to keep up with newer version of TensorFlow (1.3 , 1.4, and upcoming 1.5)
- enable XLA path
- enable RNN / LSTM / half precision CNN kernels in MIOpen
- containers for distros other than Ubuntu

**Comment by Dekken** [comment]
I'm not sure this answers my question, I'm referring to PYTHON 3 version of tensorflow, not any particular version of tensorflow

**Comment by Dekken** [comment]
As you can see at this link: https://pypi.python.org/pypi/tensorflow/1.3.0

tensorflow 1.3 - is released for multiple versions of python
