### ISSUE TITLE
Support for Hawaii

### ISSUE THREAD

**Issue by Dekken** [ROCmSoftwarePlatform/hiptensorflow#53]
Is there to be support expected for cards such as the R9 390?

Thanks

**Comment by whchung** [comment]
The only supported hardware is GFX IP 8 (Fiji) and GFX IP 9 (Vega). GFX IP 7 (Hawaii) won't be supported.

**Comment by Dekken** [comment]
Can you provide a technical reason? 

I feel very stupid for investing in AMD hardware now. 

The marketing employed I believe is highly suspect. Obviously it's my own fault for not investigating well enough, but one would IMAGINE that the 390 would be the same architecture as the 380, and just a better version, but no.

**Comment by whchung** [comment]
It's possible to build and run `HIP` / `HCC` applications on GFXIP7 (Hawaii). But not for `hiptensorflow`. Two dependent libraries, `Tensile` / `MIOpen` come with heavily tuned GCN ISA assembly kernels. And they only come with kernels for GFXIP8 (Fiji) and GFXIP9 (Vega).

**Comment by tingxingdong** [comment]
@Dekken  You may want to read this 
https://github.com/RadeonOpenCompute/ROCm

**Comment by Dekken** [comment]
@tingxingdong Thanks I'm aware GCN 2 is missing support for atomics - I was hoping for some workaround
