### ISSUE TITLE
Windows AMD gpu support?

### ISSUE THREAD

**Issue by ShrekVoid** [ROCmSoftwarePlatform/hiptensorflow#55]
Does it support AMD GPUs on windows?
The installation guide only specifies how to install on linux systems..
Could someone point me to a guide on windows?

**Comment by gstoner** [comment]
It currently does not run on Windows Hip currently is not on Windows

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by thefiddler** [comment]
Is Windows support planned in the future? If so, what would be the minimum requirement for the GPU?

Windows support is important for us, as 90% of our customers are using Windows.

**Comment by samscott1989** [comment]
totally agree Tensor Flow should be support  AMD GPU in windows...   

i dont want because Tensor Flow i have to bought another one  graphics card.

It's not worth it.

**Comment by whchung** [comment]
ROCm on Windows is still under development and I couldn't disclose a timeframe yet. Meanwhile lease kindly try https://github.com/ROCmSoftwarePlatform/tensorflow/ on Linux. This project has been deprecated and I'll close this repository very soon. Thanks for your understanding.
