### ISSUE TITLE
GPU utilization, memory consumption and temperature monitoring

### ISSUE THREAD

**Issue by evg-tyurin** [ROCmSoftwarePlatform/hiptensorflow#57]
I've started from clean Ubuntu 16.04 and completed "Basic installation" steps from the README. I run example programs and see that Tensorflow uses my GPU, that's ok.

What tool I can use to monitor GPU utilization, memory consumption and temperature? As I read from other issues I should not install additional GPU drivers which may be required by a monitoring tool.

I have RX480.

Thank you.

**Comment by sunway513** [comment]
Hi @evg-tyurin , you can use rocm-smi located under `/opt/rocm/bin` to monitor the temperature and some other information, see doc [here](https://github.com/RadeonOpenCompute/ROC-smi).
We don't currently offer to monitor of GPU utilization or memory occupancy.
