### ISSUE TITLE
Couldn't open CUDA library libMIOpen.so

### ISSUE THREAD

**Issue by mmmmming18** [ROCmSoftwarePlatform/hiptensorflow#58]
>>> import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libhipblas.so locally
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libhipfft.so locally
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libhip_hcc.so locally
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libhiprng.so locally
I tensorflow/stream_executor/dso_loader.cc:130] Couldn't open CUDA library libMIOpen.so. LD_LIBRARY_PATH: /opt/rocm/lib:/opt/rocm/lib:/usr/local/cuda/lib64
I tensorflow/stream_executor/cuda/miopen_dnn.cc:3533] Unable to load cuDNN DSO

My system is ubuntu 16.04, rocm version is 1.7.60. And gpu is vega FE.

What did I miss? Thanks!!!

**Comment by Dekken** [comment]
I'm experiencing this, what was your solution?

**Comment by mmmmming18** [comment]
@Dekken I didn't remove the cuda related env variables at first. After cleaning the os, everything works fine.
