### ISSUE TITLE
Port, Release and Support Tensorflow 1.6+

### ISSUE THREAD

**Issue by teosoft123** [ROCmSoftwarePlatform/hiptensorflow#72]
### Tensorflow 1.6 was released today. HIP Tensorflow is 1.0.1
I'm wondering if there's any plans to release and support versions that are not one year old.

**Comment by Mandrewoid** [comment]
#63

**Comment by FelixSchwarz** [comment]
>  We've been focusing on bringing up Tensorflow-rocm forked from V1.3, it will be available soon. 

source: 60ad8b65fd34845066fa078393615091449962ad

**Comment by whchung** [comment]
https://github.com/ROCmSoftwarePlatform/tensorflow
ROCm port of TensorFlow 1.3.0 has just been made public. It has been tested against ROCm stack version 1.7.1.

We are now working on enabling RNN & fp16 kernels, as well as re-sync with upstream TensorFlow.

**Comment by Bengt** [comment]
The wheel of TensorFlow 1.3 is not in the repository yet: http://repo.radeon.com/rocm/misc/tensorflow/

**Comment by whchung** [comment]
+@jedwards-AMD for awareness

**Comment by jedwards-AMD** [comment]
The 1.3.0 version of tensorflow has been uploaded to this location: http://repo.radeon.com/rocm/misc/tensorflow/tensorflow-1.3.0-cp27-cp27mu-linux_x86_64.whl

**Comment by xyang2013** [comment]
@whchung Is RNN currently working? I have Vega FE (Ubuntu 16.04.4) and not sure which driver to install to get TF 1.3 working. Thank you

**Comment by whchung** [comment]
@xyang2013 For RNN, you can find a branch at:

https://github.com/ROCmSoftwarePlatform/tensorflow/tree/rocm-v1-rnn

You won't be able to use it though, as relevant RNN kernels in MIOpen are not released yet. An upcoming MIOpen 1.3 is coming in the next couple of days and we will then merge this branch into the default branch.

**Comment by whchung** [comment]
@xyang2013 Install ROCm stack gets you required drivers `rock-dkms`, `compute-firmeware` installed.

**Comment by xyang2013** [comment]
@whchung Thank you. Is it right to assume that if RNN works, LSTM/GRU would also work?
