### ISSUE TITLE
could not install ROCm

### ISSUE THREAD

**Issue by victor-felicitas** [ROCmSoftwarePlatform/hiptensorflow#73]
I have experienced strange error while trying to install ROCm pkgs on Ubuntu 16.04 - seems like something with CDROM drivers.
I don't have cd-rom at all, maybe this is a problem?

On my old notebook (which has cd-rom) everything worked fine at this point.
Please help!

vityek@vityek-X370GTN:~$ sudo apt-get update && \
>     sudo apt-get install -y --allow-unauthenticated \
>     rocm-dkms rocm-dev rocm-libs \
>     rocm-device-libs \
>     hsa-ext-rocr-dev hsakmt-roct-dev hsa-rocr-dev \
>     rocm-opencl rocm-opencl-dev \
>     rocm-utils \
>     rocm-profiler cxlactivitylogger \
>     miopen-hip miopengemm
Ign:1 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial InRelease
Get:2 file:/var/opt/amdgpu-pro-local ./ InRelease
Ign:2 file:/var/opt/amdgpu-pro-local ./ InRelease
Ign:3 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial Release
Get:4 file:/var/opt/amdgpu-pro-local ./ Release [814 B]
Ign:5 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/main amd64 Packages
Ign:6 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/main i386 Packages
Ign:7 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/main all Packages
Ign:8 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/main Translation-en_US
Ign:9 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/main Translation-en
Ign:10 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/main amd64 DEP-11 Metadata
Ign:11 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/main DEP-11 64x64 Icons
Get:4 file:/var/opt/amdgpu-pro-local ./ Release [814 B]                              
Ign:12 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/restricted amd64 Packages
Ign:13 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/restricted i386 Packages
Ign:14 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/restricted all Packages
Get:15 file:/var/opt/amdgpu-pro-local ./ Release.gpg                                 
Ign:15 file:/var/opt/amdgpu-pro-local ./ Release.gpg                                 
Ign:16 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/restricted Translation-en_US
Ign:17 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/restricted Translation-en
Ign:18 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/restricted amd64 DEP-11 Metadata
Ign:19 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/restricted DEP-11 64x64 Icons
Ign:5 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/main amd64 Packages
Ign:6 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/main i386 Packages
Ign:7 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/main all Packages
Ign:8 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/main Translation-en_US
Ign:9 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/main Translation-en
Ign:10 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/main amd64 DEP-11 Metadata
Ign:11 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/main DEP-11 64x64 Icons
Ign:12 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/restricted amd64 Packages
Ign:13 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/restricted i386 Packages
Ign:14 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/restricted all Packages
Ign:16 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/restricted Translation-en_US
Ign:17 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/restricted Translation-en
Ign:18 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/restricted amd64 DEP-11 Metadata
Ign:19 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/restricted DEP-11 64x64 Icons
Ign:5 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/main amd64 Packages
Ign:6 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/main i386 Packages
Ign:7 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/main all Packages
Ign:8 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/main Translation-en_US
Ign:9 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/main Translation-en
Ign:10 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/main amd64 DEP-11 Metadata
Ign:11 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/main DEP-11 64x64 Icons
Ign:12 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/restricted amd64 Packages
Ign:13 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/restricted i386 Packages
Ign:14 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/restricted all Packages
Ign:16 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/restricted Translation-en_US
Ign:17 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/restricted Translation-en
Ign:18 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/restricted amd64 DEP-11 Metadata
Ign:19 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/restricted DEP-11 64x64 Icons
Ign:5 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/main amd64 Packages
Ign:6 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/main i386 Packages
Ign:7 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/main all Packages
Ign:8 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/main Translation-en_US
Ign:9 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/main Translation-en
Ign:10 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/main amd64 DEP-11 Metadata
Ign:11 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/main DEP-11 64x64 Icons
Ign:12 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/restricted amd64 Packages
Ign:13 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/restricted i386 Packages
Ign:14 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/restricted all Packages
Ign:16 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/restricted Translation-en_US
Ign:17 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/restricted Translation-en
Ign:18 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/restricted amd64 DEP-11 Metadata
Ign:19 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/restricted DEP-11 64x64 Icons
Ign:5 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/main amd64 Packages
Ign:6 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/main i386 Packages
Ign:7 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/main all Packages
Ign:8 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/main Translation-en_US
Ign:9 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/main Translation-en
Ign:10 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/main amd64 DEP-11 Metadata
Ign:11 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/main DEP-11 64x64 Icons
Ign:12 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/restricted amd64 Packages
Ign:13 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/restricted i386 Packages
Ign:14 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/restricted all Packages
Ign:16 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/restricted Translation-en_US
Ign:17 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/restricted Translation-en
Ign:18 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/restricted amd64 DEP-11 Metadata
Ign:19 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/restricted DEP-11 64x64 Icons
Err:5 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/main amd64 Packages
  Please use apt-cdrom to make this CD-ROM recognized by APT. apt-get update cannot be used to add new CD-ROMs
Ign:6 cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial/main i386 Packages
Hit:20 http://repo.yandex.ru/yandex-browser/deb beta InRelease                       
Hit:21 http://ru.archive.ubuntu.com/ubuntu xenial InRelease                          
Hit:22 http://ru.archive.ubuntu.com/ubuntu xenial-updates InRelease                  
Hit:23 http://ru.archive.ubuntu.com/ubuntu xenial-backports InRelease                
Hit:24 http://security.ubuntu.com/ubuntu xenial-security InRelease                   
Hit:25 http://ppa.launchpad.net/alexx2000/doublecmd/ubuntu xenial InRelease          
Hit:26 http://repo.radeon.com/rocm/apt/debian xenial InRelease                     
Reading package lists... Done  
W: The repository 'cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801) xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch cdrom://Ubuntu 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801)/dists/xenial/main/binary-amd64/Packages  Please use apt-cdrom to make this CD-ROM recognized by APT. apt-get update cannot be used to add new CD-ROMs
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by whchung** [comment]
@victor-felicitas please raise the ticket at: https://github.com/RadeonOpenCompute/ROCm
