### ISSUE TITLE
Couldn't open CUDA library libhipfft.so, libhiprng.so.

### ISSUE THREAD

**Issue by max0x7ba** [ROCmSoftwarePlatform/hiptensorflow#74]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

I googled and got 11 search results total, none helped.

### Environment info
Operating System:
```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
```

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

No CUDA installed.

If installed from binary pip package, provide:

1. A link to the pip package you installed:

http://repo.radeon.com/rocm/misc/tensorflow/tensorflow-1.0.1-cp27-cp27mu-linux_x86_64.whl

2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
```
$ python -c "import tensorflow; print(tensorflow.__version__)"
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libhipblas.so locally
I tensorflow/stream_executor/dso_loader.cc:130] Couldn't open CUDA library libhipfft.so. LD_LIBRARY_PATH: 
I tensorflow/stream_executor/cuda/cuda_fft.cc:344] Unable to load cuFFT DSO.
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libhip_hcc.so locally
I tensorflow/stream_executor/dso_loader.cc:130] Couldn't open CUDA library libhiprng.so. LD_LIBRARY_PATH: 
I tensorflow/stream_executor/cuda/cuda_rng.cc:338] Unable to load cuRAND DSO.
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libMIOpen.so locally
1.0.1
```

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

I followed the instructions to install ROCm pkgs, however, libraries `libhipfft.so`, `libhiprng.so` are missing, see the above output of `import tensorflow`.

### What other attempted solutions have you tried?

Removed and installed again the libraries from `deb [arch=amd64] http://repo.radeon.com/rocm/apt/debian/ xenial main` repo.

**Comment by Mandrewoid** [comment]
In no particular order: 
libhiprng.so is provided by package "rocrand" but I believe it is provided as libhiprand.so
I just symlinked it to /opt/rocm/lib/libhiprng.so and it works fine

libhipfft.so is provided by package "hcfft" as /opt/rocm/hcfft/lib/libhipfft.so 
It is possible this was symlinked automatically to opt/rocm/lib/libhipfft.so but it might not have been.

What I can tell you is my startup messages are all successful. 
Good luck!

**Comment by whchung** [comment]
Please kindly try https://github.com/ROCmSoftwarePlatform/tensorflow/ and open the issue there in case it persists. This project has been deprecated and I'll close this repository very soon. Thanks for your understanding.
