### ISSUE TITLE
Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by Chern2** [ROCmSoftwarePlatform/hiptensorflow#76]
I installed hiptensorflow following https://github.com/ROCmSoftwarePlatform/hiptensorflow/blob/hip/rocm_docs/tensorflow-quickstart.md. I am not really sure that all have been installed correctly. But I tried to run my model, a problem arises. By the way, my platform is ubuntu 16.04 + r7 1800x +Vega56. Here is error information:

Traceback (most recent call last):
  File "train.py", line 1, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 61, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: _ZN8hip_impl18unlock_stream_hip_EP12ihipStream_tPvPKcPN2hc16accelerator_viewE

Failed to load the native TensorFlow runtime.

See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#import_error

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by Mandrewoid** [comment]
Don't worry, you aren't alone. If you search on github specifically for the symbol that is undefined, there are a few cases like yours. Including myself.
https://github.com/RadeonOpenCompute/ROCm/issues/351#issuecomment-372562986
Might be worth checking out 
https://github.com/ROCmSoftwarePlatform/hiptensorflow/pull/75
As well, depending on how deep you want to go. 
I found that upgrading my ROCm broke tensorflow, so I downgraded and it works fine again.

**Comment by Chern2** [comment]
@Mandrewoid What kind of ROCm version do you use now?  Dose this problem happen only in  version 1.7? Vega family products are supported by ROCm after version 1.6.

**Comment by Mandrewoid** [comment]
@Chern2 I don't actually know for sure what ROCm version I have, or am running, but my card is a vega FE, and the output of rocminfo says : 
Runtime Version:         1.1

**Comment by Chern2** [comment]
@Mandrewoid vega fe should be one of vega family. I think the version that you are using should support my GPU. Can you tell me how to downgrade  ROCm ?

**Comment by Mandrewoid** [comment]
Hmm that's a question that's rather difficult for me to answer because I'm not an expert on package management.... For me, I just installed it from the dpkg cache file, but if you never had an old version installed, this won't be a possibility. 
I think perhaps it is time to ask @gstoner ? I'm not sure if the AMD repo (http://repo.radeon.com/rocm/apt/debian/)
contains previous versions at all? I just looked and I didn't find any obvious ones.
Greg, I think if this currently isn't possible (aka the old packages are removed when the new release happens) something should be done to change that policy because if an update gets pushed that breaks compatibility with a library (like hiptensorflow), people doing fresh first-time installs like @Chern2 will be stuck and get frustrated with the whole ROCm ecosystem.

**Comment by sunway513** [comment]
Hi @Chern2 @Mandrewoid , as stated in the [rocm readme](https://github.com/ROCmSoftwarePlatform/hiptensorflow/blob/hip/README.ROCm.md), we are deprecating this repository, and will soon provide access to the ROCm support of TF1.3.  

The only recommended way to try hipTF is to follow the instruction and use our prepared docker image, please find it here
`https://hub.docker.com/r/rocm/hiptensorflow/tags/`

**Comment by Mandrewoid** [comment]
@sunway513 Is there anything I can do to help get 1.3 out? Testing/building, etc

**Comment by sunway513** [comment]
Thanks @Mandrewoid ! We have just released the TF1.3, please take a look and let us know if you can spot any issues:
https://github.com/ROCmSoftwarePlatform/tensorflow
