### ISSUE TITLE
Inverted colors on tensorflow Cyclegan training

### ISSUE THREAD

**Issue by victor-felicitas** [ROCmSoftwarePlatform/hiptensorflow#77]
Hello!

I am trying to use hip-tensorflow to train Cyclegan for image style transfer.
I have tried several tensorflow and 1 tensorlayer implementations.
However, all of them do not work as intended on latest 1.7 ROCM.

I am using datasets provided by original Cyclegan research authors.
For example, horses2zebras after 20 epochs training result in
![image](https://user-images.githubusercontent.com/36967768/38038442-a119e472-32b3-11e8-9fc0-f849c0c9107d.png)

Another Cyclegan implementation on tensorflow produces mistake after training for ~6 hours on any dataset (Nan in summary histogram for: D_X/fake) and only existing tensorlayer implementation gives inverted colors after ~60 epochs.

I am using default training settings in all cases.
Do I need to change something to train models on hiptensorflow?
Any advice will be appreciated!

I am running Ubuntu 16.04, ROCM is installed correctly.
Using ready-made models for testing on images provide fine results.

**Comment by whchung** [comment]
@victor-felicitas `hiptensorflow` is deprecated and won't be supported anymore. I'm wondering could you try the experiment on our 1.3.0 port at: https://github.com/ROCmSoftwarePlatform/tensorflow/ ?

**Comment by victor-felicitas** [comment]
Hi whchung,

Thanks for advice.
Installation wasn't easy but I did it) I have uninstalled and then reinstalled ROCM, then new 1.3.0 port. 

1. Tensorlayer doesn't work at all (latest one,  1.8.2). It starts producing "nans" just after few images (previously on Hiptensorflow usually after 20 epochs):
MIOpen(HIP): Warning [ReadFile] File is unreadable.
2018-03-28 22:28:36.702796: I tensorflow/core/kernels/conv_grad_filter_ops.cc:778] running auto-tune for Backward-Filter
Epoch: [ 0/200] [   0/ 962] time: 6.9029s, d_a_loss: 1.37527776, d_b_loss: 1.31791472, g_a2b_loss: 15.03253937, g_b2a_loss: 14.50654793
Epoch: [ 0/200] [   1/ 962] time: 8.2081s, d_a_loss: 1.37571788, d_b_loss: 1.04721189, g_a2b_loss: 14.28902340, g_b2a_loss: 24.05783653
Epoch: [ 0/200] [   2/ 962] time: 9.5081s, d_a_loss: nan, d_b_loss: 1.17257118, g_a2b_loss: 13.90826225, g_b2a_loss: 12.06676006
Epoch: [ 0/200] [   3/ 962] time: 10.7490s, d_a_loss: nan, d_b_loss: 1.47950280, g_a2b_loss: 12.46980953, g_b2a_loss: nan
Epoch: [ 0/200] [   4/ 962] time: 11.6198s, d_a_loss: nan, d_b_loss: nan, g_a2b_loss: nan, g_b2a_loss: nan

2. At least one tensorflow implementation works - Tensorflow-simple. Before it produced completely unrecognizable images. I will report about its performance later as some epochs need to pass

**Comment by whchung** [comment]
@victor-felicitas please kindly open the ticket at https://github.com/ROCmSoftwarePlatform/tensorflow as I'll take this repository down very soon.
